# Generated by Django 5.2.6 on 2025-09-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ICUConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('hospital_number', models.CharField(max_length=50)),
                ('ward', models.CharField(max_length=100)),
                ('bed_ready', models.CharField(blank=True, max_length=50)),
                ('request_datetime', models.DateTimeField()),
                ('requesting_discipline', models.CharField(max_length=100)),
                ('reason', models.JSONField(default=list)),
                ('reason_other', models.CharField(blank=True, max_length=255)),
                ('clinical_summary', models.TextField(blank=True)),
                ('airway_patent', models.BooleanField(default=False)),
                ('airway_threatened', models.BooleanField(default=False)),
                ('intubated', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('breathing_spo2', models.PositiveIntegerField(blank=True, null=True)),
                ('breathing_distress', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('breathing_device', models.CharField(blank=True, max_length=100)),
                ('circulation_bp', models.CharField(blank=True, max_length=20)),
                ('circulation_inotropes', models.BooleanField(default=False)),
                ('circulation_anti_hpt', models.BooleanField(default=False)),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('heart_rhythm', models.CharField(blank=True, max_length=50)),
                ('fluid_type', models.CharField(blank=True, max_length=100)),
                ('fluid_urine_output', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('measures', models.CharField(blank=True, max_length=255)),
                ('gcs', models.CharField(blank=True, max_length=10)),
                ('sedation', models.BooleanField(default=False)),
                ('pupils', models.CharField(blank=True, max_length=50)),
                ('latest_abg', models.TextField(blank=True)),
                ('key_labs', models.TextField(blank=True)),
                ('imaging_findings', models.TextField(blank=True)),
                ('time_tests_done', models.DateTimeField(blank=True, null=True)),
                ('airway', models.CharField(blank=True, max_length=100)),
                ('ventilation', models.CharField(blank=True, max_length=100)),
                ('iv_fluids', models.CharField(blank=True, max_length=100)),
                ('inotropes', models.CharField(blank=True, max_length=100)),
                ('antibiotics', models.CharField(blank=True, max_length=100)),
                ('other_interventions', models.CharField(blank=True, max_length=255)),
                ('assessment', models.TextField(blank=True)),
                ('decision', models.CharField(blank=True, choices=[('admit', 'Admit to ICU'), ('not_for_icu', 'Not for ICU'), ('review_later', 'Review Later')], max_length=20)),
                ('plan_comments', models.TextField(blank=True)),
                ('consultant_name', models.CharField(blank=True, max_length=255)),
                ('signature', models.CharField(blank=True, max_length=255)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=20)),
                ('submitted', models.BooleanField(default=False)),
            ],
        ),
    ]
