# Generated by Django 5.2.6 on 2025-09-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consults', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icuconsultation',
            name='bed_ready',
        ),
        migrations.AddField(
            model_name='icuconsultation',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Enter if available, system can calculate age', null=True),
        ),
        migrations.AddField(
            model_name='icuconsultation',
            name='requesting_dr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='icuconsultation',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Enter if DOB is not known', null=True),
        ),
        migrations.AlterField(
            model_name='icuconsultation',
            name='requesting_discipline',
            field=models.CharField(choices=[('anaesthesia', 'Anaesthesia'), ('cardiology', 'Cardiology'), ('cardiothoracic surgery', 'Cardiothoracic Surgery'), ('dermatology', 'Dermatology'), ('ent surgery', 'ENT Surgery'), ('gastroenterology surgery', 'Gastroenterology Surgery'), ('General Surgery', 'General Surgery'), ('internal medicine', 'Internal Medicine'), ('maxillofacial surgery', 'Maxillofacial Surgery'), ('nephrology', 'Nephrology'), ('neurology', 'Neurology'), ('neurosurgery', 'Neurosurgery'), ('obstetrics and gynaecology', 'Obstetrics and Gynaecology'), ('oncology', 'Oncology'), ('orthopaedics surgery', 'Orthopaedics Surgery'), ('paediatrics', 'Paediatrics'), ('urology', 'Urology')], max_length=100),
        ),
        migrations.AlterField(
            model_name='icuconsultation',
            name='ward',
            field=models.CharField(choices=[('emergency unit', 'Emergency Unit'), ('ward a', 'Ward A'), ('ward b', 'Ward B'), ('ward c', 'Ward C'), ('ward d', 'Ward D'), ('ward e', 'Ward E'), ('ward f', 'Ward F'), ('ward g', 'Ward G'), ('ward h', 'Ward H'), ('ward i', 'Ward I'), ('ward j', 'Ward J'), ('ward k', 'Ward K'), ('ward l', 'Ward L'), ('ward m', 'Ward M'), ('ward n', 'Ward N'), ('ward o', 'Ward O'), ('ward p', 'Ward P'), ('ward q', 'Ward Q'), ('ward r', 'Ward R'), ('ward s', 'Ward S'), ('ward t', 'Ward T')], max_length=100),
        ),
    ]
