# Generated by Django 5.2.6 on 2025-09-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consults', '0002_remove_icuconsultation_bed_ready_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icuconsultation',
            name='requesting_dr_contact',
            field=models.CharField(blank=True, help_text="Enter the requesting doctor's contact info", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='icuconsultation',
            name='requesting_dr_speed_dial',
            field=models.CharField(blank=True, help_text="Enter the requesting doctor's speed dial", max_length=20, null=True),
        ),
    ]
