# Generated by Django 5.2.6 on 2025-09-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consults', '0003_icuconsultation_requesting_dr_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icuconsultation',
            name='clinical_summary',
            field=models.TextField(blank=True, help_text='Brief clinical summary of the patient', null=True),
        ),
    ]
