# Generated by Django 5.2.6 on 2025-09-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consults', '0004_alter_icuconsultation_clinical_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icuconsultation',
            name='clinical_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
