# Generated by Django 5.2.6 on 2025-09-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consults', '0005_alter_icuconsultation_clinical_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icuconsultation',
            name='circulation_bp',
        ),
        migrations.AddField(
            model_name='icuconsultation',
            name='bp_diastolic',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icuconsultation',
            name='bp_systolic',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icuconsultation',
            name='sedation',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
    ]
