# Generated by Django 5.2.6 on 2025-10-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consults', '0006_remove_icuconsultation_circulation_bp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icuconsultation',
            name='fluid_type',
            field=models.CharField(blank=True, choices=[('fluid_type1', 'Fluid Type 1'), ('fluid_type2', 'Fluid Type 2'), ('fluid_type3', 'Fluid Type 3')], max_length=100),
        ),
        migrations.AlterField(
            model_name='icuconsultation',
            name='heart_rhythm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
