# Generated by Django 5.2.6 on 2025-11-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consults', '0007_alter_icuconsultation_fluid_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icuconsultation',
            name='circulation_anti_hpt',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='Antihypertensives?'),
        ),
        migrations.AlterField(
            model_name='icuconsultation',
            name='circulation_inotropes',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='On inotropes?'),
        ),
    ]
