# Generated by Django 5.2.6 on 2025-11-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consults', '0008_alter_icuconsultation_circulation_anti_hpt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icuconsultation',
            name='breathing_distress',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='icuconsultation',
            name='circulation_anti_hpt',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True, verbose_name='Antihypertensives?'),
        ),
        migrations.AlterField(
            model_name='icuconsultation',
            name='circulation_inotropes',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True, verbose_name='On inotropes?'),
        ),
        migrations.AlterField(
            model_name='icuconsultation',
            name='intubated',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='icuconsultation',
            name='sedation',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
    ]
